# Generated by Django 5.0.6 on 2024-05-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIAnalysisLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_path", models.CharField(blank=True, max_length=255, null=True)),
                ("success", models.BooleanField()),
                ("message", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "class_id",
                    models.IntegerField(blank=True, db_column="class", null=True),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("request_timestamp", models.DateTimeField(blank=True, null=True)),
                ("response_timestamp", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "ai_analysis_log",
            },
        ),
    ]
